# Generated by Django 4.0.1 on 2022-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunmybotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_key', models.TextField()),
                ('conf_value', models.TextField()),
                ('conf_description', models.TextField()),
            ],
        ),
    ]
